<?xml version="1.0" encoding="utf-8" ?>
<!-- Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information. -->
<Spec xmlns="http://IxMilia.com/Dxf/EntitiesSpec">
  <!--
  
  ENTITY - the abstract base of all of the following types
  
  -->
  <Entity Name="DxfEntity" EntityType="" SubclassMarker="" TypeString="">
    <Property Name="Handle" Code="5" Type="string" DefaultValue="null" />
    <!-- 102 codes app defined -->
    <!-- 102 codes ({ACAD_REACTORS) around code 330 -->
    <!-- 102 codes ({ACAD_XDICTIONARY) around code 360 -->
    <Property Name="OwnerHandle" Code="330" Type="string" DefaultValue="null" MinVersion="R2000" />
    <!-- subclass marker 100,AcDbEntity -->
    <Property Name="IsInPaperSpace" Code="67" Type="bool" DefaultValue="false" ReadConverter="BoolShort" WriteConverter="BoolShort" DisableWritingDefault="true" MinVersion="R12" />
    <Property Name="Layer" Code="8" Type="string" DefaultValue="0" />
    <Property Name="LinetypeName" Code="6" Type="string" DefaultValue="BYLAYER" DisableWritingDefault="true" />
    <Property Name="Elevation" Code="38" Type="double" DefaultValue="0.0" DisableWritingDefault="true" MaxVersion="R12" />
    <Property Name="MaterialHandle" Code="347" Type="string" DefaultValue="BYLAYER" DisableWritingDefault="true" MinVersion="R2007" />
    <Property Name="Color" Code="62" Type="DxfColor" DefaultValue="DxfColor.ByLayer" ReadConverter="DxfColor.FromRawValue" WriteConverter="DxfColor.GetRawValue" DisableWritingDefault="true" />
    <Property Name="LineweightEnumValue" Code="370" Type="short" DefaultValue="0" MinVersion="R2000" />
    <Property Name="LinetypeScale" Code="48" Type="double" DefaultValue="1.0" DisableWritingDefault="true" MinVersion="R13" />
    <Property Name="IsVisible" Code="60" Type="bool" DefaultValue="true" ReadConverter="!BoolShort" WriteConverter="NotBoolShort" DisableWritingDefault="true" MinVersion="R13" />
    <Property Name="ImageByteCount" Code="92" Type="int" DefaultValue="0" DisableWritingDefault="true" MinVersion="R2000" />
    <Property Name="PreviewImageData" Code="310" Type="string" DefaultValue="null" AllowMultiples="true" MinVersion="R2000" />
    <Property Name="Color24Bit" Code="420" Type="int" DefaultValue="0" MinVersion="R2004" />
    <Property Name="ColorName" Code="430" Type="string" DefaultValue="null" MinVersion="R2004" />
    <Property Name="Transparency" Code="440" Type="int" DefaultValue="0" MinVersion="R2004" />
    <Property Name="PlotStyleHandle" Code="390" Type="string" DefaultValue="null" MinVersion="R2007" />
    <Property Name="ShadowMode" Code="284" Type="DxfShadowMode" DefaultValue="DxfShadowMode.CastsAndReceivesShadows" ReadConverter="(DxfShadowMode)" WriteConverter="(short)" MinVersion="R2007" />
  </Entity>
  <!--
  
  3DFACE
  
  -->
  <Entity Name="Dxf3DFace" EntityType="Face" SubclassMarker="AcDbFace" TypeString="3DFACE">
    <Property Name="FirstCorner" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="SecondCorner" Code="11" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="11,21,31" />
    <Property Name="ThirdCorner" Code="12" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="12,22,32" />
    <Property Name="FourthCorner" Code="13" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="13,23,33" />
    <Property Name="EdgeFlags" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" DisableWritingDefault="true">
      <Flag Name="IsFirstEdgeInvisible" Mask="1" />
      <Flag Name="IsSecondEdgeInvisible" Mask="2" />
      <Flag Name="IsThirdEdgeInvisible" Mask="4" />
      <Flag Name="IsFourthEdgeInvisible" Mask="8" />
    </Property>
  </Entity>
  <!--
  
  3DSOLID
  
  -->
  <Entity Name="Dxf3DSolid" EntityType="ModelerGeometry" SubclassMarker="AcDbModelerGeometry" TypeString="3DSOLID" MinVersion="R13">
    <Property Name="FormatVersionNumber" Code="70" Type="short" DefaultValue="1" />
    <Property Name="CustomData" Code="1" Type="string" DefaultValue="null" AllowMultiples="true" />
    <Property Name="CustomData2" Code="3" Type="string" DefaultValue="null" AllowMultiples="true" />
  </Entity>
  <!--
  
  ACAD_PROXY_ENTITY
  
  -->
  <Entity Name="DxfProxyEntity" EntityType="ProxyEntity" SubclassMarker="AcDbProxyEntity" TypeString="ACAD_PROXY_ENTITY" MinVersion="R14">
    <Property Name="ProxyEntityClassId" Code="90" Type="int" DefaultValue="498" />
    <Property Name="ApplicationEntityClassId" Code="91" Type="int" DefaultValue="500" />
    <Property Name="GraphicsDataSize" Code="92" Type="int" DefaultValue="0" />
    <Property Name="GraphicsDataString" Code="310" Type="string" DefaultValue="null" AllowMultiples="true" />
    <Property Name="EntityDataSize" Code="93" Type="int" DefaultValue="0" />
    <Property Name="EntityDataString" Code="310" Type="string" DefaultValue="null" AllowMultiples="true" />
    <Property Name="ObjectID1" Code="330" Type="string" DefaultValue="null" />
    <Property Name="ObjectID2" Code="340" Type="string" DefaultValue="null" />
    <Property Name="ObjectID3" Code="350" Type="string" DefaultValue="null" />
    <Property Name="ObjectID4" Code="360" Type="string" DefaultValue="null" />
    <Property Name="Terminator" Code="94" Type="int" DefaultValue="0" />
    <Property Name="ObjectDrawingFormat" Code="95" Type="uint" DefaultValue="0" ReadConverter="(uint)" WriteConverter="(int)" Accessibility="private" MinVersion="R2000" />
    <Property Name="OriginalDataFormatIsDxf" Code="70" Type="bool" DefaultValue="true" ReadConverter="BoolShort" WriteConverter="BoolShort" MinVersion="R2000" />
  </Entity>
  <!--
  
  ARC
  
  -->
  <Entity Name="DxfArc" EntityType="Arc" SubclassMarker="AcDbArc" TypeString="ARC" BaseClass="DxfCircle">
    <Property Name="StartAngle" Code="50" Type="double" DefaultValue="0.0" />
    <Property Name="EndAngle" Code="51" Type="double" DefaultValue="360.0" />
    <Constructor>
      <ConstructorParameter Property="Center" Type="DxfPoint" />
      <ConstructorParameter Property="Radius" Type="double" />
      <ConstructorParameter Property="StartAngle" Type="double" />
      <ConstructorParameter Property="EndAngle" Type="double" />
    </Constructor>
  </Entity>
  <!--
  
  ARCALIGNEDTEXT
  
  -->
  <Entity Name="DxfArcAlignedText" EntityType="ArcAlignedText" SubclassMarker="AcDbArcAlignedText" TypeString="ARCALIGNEDTEXT" MinVersion="R2000">
    <Property Name="Text" Code="1" Type="string" DefaultValue="null" />
    <Property Name="FontName" Code="2" Type="string" DefaultValue="null" />
    <Property Name="BigfontName" Code="3" Type="string" DefaultValue="null" />
    <Property Name="TextStyleName" Code="7" Type="string" DefaultValue="null" />
    <Property Name="CenterPoint" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="ArcRadius" Code="40" Type="double" DefaultValue="0.0" />
    <Property Name="WidthFactor" Code="41" Type="double" DefaultValue="1.0" />
    <Property Name="TextHeight" Code="42" Type="double" DefaultValue="0.0" />
    <Property Name="CharacterSpacing" Code="43" Type="double" DefaultValue="0.0" />
    <Property Name="OffsetFromArc" Code="44" Type="double" DefaultValue="0.0" />
    <Property Name="RightOffset" Code="45" Type="double" DefaultValue="0.0" />
    <Property Name="LeftOffset" Code="46" Type="double" DefaultValue="0.0" />
    <Property Name="StartAngle" Code="50" Type="double" DefaultValue="0.0" />
    <Property Name="EndAngle" Code="51" Type="double" DefaultValue="0.0" />
    <Property Name="IsCharacterOrderReversed" Code="70" Type="bool" DefaultValue="false" ReadConverter="BoolShort" WriteConverter="BoolShort" />
    <Property Name="DirectionFlag" Code="71" Type="short" DefaultValue="0" />
    <Property Name="AlignmentFlag" Code="72" Type="short" DefaultValue="0" />
    <Property Name="SideFlag" Code="73" Type="short" DefaultValue="0" />
    <Property Name="IsBold" Code="74" Type="bool" DefaultValue="false" ReadConverter="BoolShort" WriteConverter="BoolShort" />
    <Property Name="IsItalic" Code="75" Type="bool" DefaultValue="false" ReadConverter="BoolShort" WriteConverter="BoolShort" />
    <Property Name="IsUnderline" Code="76" Type="bool" DefaultValue="false" ReadConverter="BoolShort" WriteConverter="BoolShort" />
    <Property Name="CharacterSetValue" Code="77" Type="short" DefaultValue="0" />
    <Property Name="PitchAndFamilyValue" Code="78" Type="short" DefaultValue="0" />
    <Property Name="FontType" Code="79" Type="DxfFontType" DefaultValue="DxfFontType.TTF" ReadConverter="(DxfFontType)" WriteConverter="(short)" />
    <Property Name="ColorIndex" Code="90" Type="int" DefaultValue="0" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Property Name="WizardFlag" Code="280" Type="short" DefaultValue="0" />
    <Property Name="HandleId" Code="330" Type="string" DefaultValue="null" />
  </Entity>
  <!--
  
  ATTDEF
  
  -->
  <Entity Name="DxfAttributeDefinition" EntityType="AttributeDefinition" SubclassMarker="null" TypeString="ATTDEF">
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Location" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="TextHeight" Code="40" Type="double" DefaultValue="1.0" />
    <Property Name="Value" Code="1" Type="string" DefaultValue="null" />
    <Property Name="Rotation" Code="50" Type="double" DefaultValue="0" DisableWritingDefault="true" />
    <Property Name="RelativeXScaleFactor" Code="41" Type="double" DefaultValue="1.0" DisableWritingDefault="true" />
    <Property Name="ObliqueAngle" Code="51" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="TextStyleName" Code="7" Type="string" DefaultValue="STANDARD" DisableWritingDefault="true" />
    <Property Name="TextGenerationFlags" Code="71" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" DisableWritingDefault="true">
      <Flag Name="IsTextBackward" Mask="2" />
      <Flag Name="IsTextUpsideDown" Mask="4" />
    </Property>
    <Property Name="HorizontalTextJustification" Code="72" Type="DxfHorizontalTextJustification" DefaultValue="DxfHorizontalTextJustification.Left" ReadConverter="(DxfHorizontalTextJustification)" WriteConverter="(short)" DisableWritingDefault="true" />
    <Property Name="SecondAlignmentPoint" Code="11" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="11,21,31" />
    <Property Name="Normal" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Property Name="Prompt" Code="3" Type="string" DefaultValue="null" />
    <Property Name="Tag" Code="2" Type="string" DefaultValue="null" />
    <Property Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)">
      <Flag Name="IsInvisible" Mask="1" />
      <Flag Name="IsConstant" Mask="2" />
      <Flag Name="IsInputVerificationRequired" Mask="4" />
      <Flag Name="IsAttributePresent" Mask="8" />
    </Property>
    <Property Name="FieldLength" Code="73" Type="short" DefaultValue="0" DisableWritingDefault="true" />
    <Property Name="VerticalTextJustification" Code="74" Type="DxfVerticalTextJustification" DefaultValue="DxfVerticalTextJustification.Baseline" ReadConverter="(DxfVerticalTextJustification)" WriteConverter="(short)" DisableWritingDefault="true" MinVersion="R12" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value="AcDbText" MinVersion="R13" />
      <WriteProperty Property="Thickness" />
      <WriteProperty Property="Location" />
      <WriteProperty Property="TextHeight" />
      <WriteProperty Property="Value" />
      <WriteSpecificValue Code="100" Value="AcDbAttributeDefinition" MinVersion="R13" />
      <WriteProperty Property="Rotation" />
      <WriteProperty Property="RelativeXScaleFactor" />
      <WriteProperty Property="ObliqueAngle" />
      <WriteProperty Property="TextStyleName" />
      <WriteProperty Property="TextGenerationFlags" />
      <WriteProperty Property="HorizontalTextJustification" />
      <WriteProperty Property="SecondAlignmentPoint" />
      <WriteProperty Property="Normal" />
      <WriteSpecificValue Code="100" Value="AcDbAttributeDefinition" MinVersion="R13" />
      <WriteProperty Property="Prompt" />
      <WriteProperty Property="Tag" />
      <WriteProperty Property="Flags" />
      <WriteProperty Property="FieldLength" />
      <WriteProperty Property="VerticalTextJustification" />
    </WriteOrder>
  </Entity>
  <!--
  
  ATTRIB
  
  -->
  <Entity Name="DxfAttribute" EntityType="Attribute" SubclassMarker="null" TypeString="ATTRIB">
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Location" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="TextHeight" Code="40" Type="double" DefaultValue="1.0" />
    <Property Name="Value" Code="1" Type="string" DefaultValue="null" />
    <Property Name="Tag" Code="2" Type="string" DefaultValue="null" />
    <Property Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)">
      <Flag Name="IsInvisible" Mask="1" />
      <Flag Name="IsConstant" Mask="2" />
      <Flag Name="IsInputVerificationRequired" Mask="4" />
      <Flag Name="IsAttributePresent" Mask="8" />
    </Property>
    <Property Name="FieldLength" Code="73" Type="short" DefaultValue="0" DisableWritingDefault="true" />
    <Property Name="Rotation" Code="50" Type="double" DefaultValue="0" DisableWritingDefault="true" />
    <Property Name="RelativeXScaleFactor" Code="41" Type="double" DefaultValue="1.0" DisableWritingDefault="true" />
    <Property Name="ObliqueAngle" Code="51" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="TextStyleName" Code="7" Type="string" DefaultValue="STANDARD" DisableWritingDefault="true" />
    <Property Name="TextGenerationFlags" Code="71" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" DisableWritingDefault="true">
      <Flag Name="IsTextBackward" Mask="2" />
      <Flag Name="IsTextUpsideDown" Mask="4" />
    </Property>
    <Property Name="HorizontalTextJustification" Code="72" Type="DxfHorizontalTextJustification" DefaultValue="DxfHorizontalTextJustification.Left" ReadConverter="(DxfHorizontalTextJustification)" WriteConverter="(short)" DisableWritingDefault="true" />
    <Property Name="VerticalTextJustification" Code="74" Type="DxfVerticalTextJustification" DefaultValue="DxfVerticalTextJustification.Baseline" ReadConverter="(DxfVerticalTextJustification)" WriteConverter="(short)" DisableWritingDefault="true" MinVersion="R12" />
    <Property Name="SecondAlignmentPoint" Code="11" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="11,21,31" />
    <Property Name="Normal" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value="AcDbText" MinVersion="R13" />
      <WriteProperty Property="Thickness" />
      <WriteProperty Property="Location" />
      <WriteProperty Property="TextHeight" />
      <WriteProperty Property="Value" />
      <WriteSpecificValue Code="100" Value="AcDbAttribute" MinVersion="R13" />
      <WriteProperty Property="Tag" />
      <WriteProperty Property="Flags" />
      <WriteProperty Property="FieldLength" />
      <WriteProperty Property="Rotation" />
      <WriteProperty Property="RelativeXScaleFactor" />
      <WriteProperty Property="ObliqueAngle" />
      <WriteProperty Property="TextStyleName" />
      <WriteProperty Property="TextGenerationFlags" />
      <WriteProperty Property="HorizontalTextJustification" />
      <WriteProperty Property="VerticalTextJustification" />
      <WriteProperty Property="SecondAlignmentPoint" />
      <WriteProperty Property="Normal" />
    </WriteOrder>
  </Entity>
  <!--
  
  BODY
  
  -->
  <Entity Name="DxfBody" EntityType="Body" SubclassMarker="AcDbModelerGeometry" TypeString="BODY" MinVersion="R13">
    <Property Name="FormatVersionNumber" Code="70" Type="short" DefaultValue="1" />
    <Property Name="CustomData" Code="1" Type="string" DefaultValue="null" AllowMultiples="true" />
    <Property Name="CustomData2" Code="3" Type="string" DefaultValue="null" AllowMultiples="true" />
  </Entity>
  <!--
  
  CIRCLE
  
  -->
  <Entity Name="DxfCircle" EntityType="Circle" SubclassMarker="AcDbCircle" TypeString="CIRCLE">
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Center" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="Radius" Code="40" Type="double" DefaultValue="0.0" />
    <Property Name="Normal" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Constructor>
      <ConstructorParameter Property="Center" Type="DxfPoint" />
      <ConstructorParameter Property="Radius" Type="double" />
    </Constructor>
  </Entity>
  <!--
  
  DIMENSION
  
  -->
  <!-- the class from which all dimensions inherit -->
  <Entity Name="DxfDimensionBase" EntityType="Dimension" SubclassMarker="AcDbDimension" TypeString="DIMENSION" DefaultConstructor="Internal" CopyConstructor="Protected">
    <Property Name="DimensionVersion" Code="280" Type="DxfDimensionVersion" DefaultValue="DxfDimensionVersion.R2010" ReadConverter="(DxfDimensionVersion)" WriteConverter="(short)" MinVersion="R2010" />
    <Property Name="BlockName" Code="2" Type="string" DefaultValue="null" />
    <Property Name="DefinitionPoint1" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="TextMidPoint" Code="11" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="11,21,31" />
    <Property Name="DimensionType" Code="70" Type="DxfDimensionType" DefaultValue="DxfDimensionType.RotatedHorizontalOrVertical" ReadConverter="(DxfDimensionType)" WriteConverter="(short)" />
    <Property Name="AttachmentPoint" Code="71" Type="DxfAttachmentPoint" DefaultValue="DxfAttachmentPoint.TopLeft" ReadConverter="(DxfAttachmentPoint)" WriteConverter="(short)" MinVersion="R2000" />
    <Property Name="TextLineSpacingStyle" Code="72" Type="DxfTextLineSpacingStyle" DefaultValue="DxfTextLineSpacingStyle.AtLeast" ReadConverter="(DxfTextLineSpacingStyle)" WriteConverter="(short)" DisableWritingDefault="true" MinVersion="R2000" />
    <Property Name="TextLineSpacingFactor" Code="41" Type="double" DefaultValue="1.0" DisableWritingDefault="true" MinVersion="R2000" />
    <Property Name="ActualMeasurement" Code="42" Type="double" DefaultValue="0.0" DisableWritingDefault="true" ProtectedSet="true" MinVersion="R2000" />
    <Property Name="Text" Code="1" Type="string" DefaultValue="&lt;&gt;" />
    <Property Name="TextRotationAngle" Code="53" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="HorizontalDirectionAngle" Code="51" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Normal" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Property Name="DimensionStyleName" Code="3" Type="string" DefaultValue="null" MinVersion="R12" />
  </Entity>
  <!-- rotated, horizontal, or vertical; type 0 -->
  <Entity Name="DxfRotatedDimension" EntityType="Dimension" SubclassMarker="AcDbAlignedDimension" TypeString="" BaseClass="DxfDimensionBase" CopyConstructor="Inherited" Tag="RotatedHorizontalOrVertical">
    <Property Name="InsertionPoint" Code="12" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="12,22,32" />
    <Property Name="DefinitionPoint2" Code="13" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="13,23,33" />
    <Property Name="DefinitionPoint3" Code="14" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="14,24,34" />
    <Property Name="RotationAngle" Code="50" Type="double" DefaultValue="0.0" />
    <Property Name="ExtensionLineAngle" Code="52" Type="double" DefaultValue="0.0" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value="AcDbAlignedDimension" MinVersion="R13" />
      <WriteProperty Property="InsertionPoint" />
      <WriteProperty Property="DefinitionPoint2" />
      <WriteProperty Property="DefinitionPoint3" />
      <WriteProperty Property="RotationAngle" />
      <WriteProperty Property="ExtensionLineAngle" />
      <WriteSpecificValue Code="100" Value="AcDbRotatedDimension" MinVersion="R13" />
    </WriteOrder>
  </Entity>
  <!-- aligned; type 1 -->
  <Entity Name="DxfAlignedDimension" EntityType="Dimension" SubclassMarker="AcDbAlignedDimension" TypeString="" BaseClass="DxfDimensionBase" CopyConstructor="Inherited" Tag="Aligned">
    <Property Name="InsertionPoint" Code="12" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="12,22,32" />
    <Property Name="DefinitionPoint2" Code="13" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="13,23,33" />
    <Property Name="DefinitionPoint3" Code="14" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="14,24,34" />
  </Entity>
  <!-- angular; type 2 -->
  <Entity Name="DxfAngularDimension" EntityType="Dimension" SubclassMarker="AcDb3PointAngularDimension" TypeString="" BaseClass="DxfDimensionBase" CopyConstructor="Inherited" Tag="Angular">
    <Property Name="DefinitionPoint2" Code="13" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="13,23,33" />
    <Property Name="DefinitionPoint3" Code="14" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="14,24,34" />
    <Property Name="DefinitionPoint4" Code="15" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="15,25,35" />
    <Property Name="DefinitionPoint5" Code="16" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="16,26,36" />
  </Entity>
  <!-- diameter; type 3 -->
  <Entity Name="DxfDiameterDimension" EntityType="Dimension" SubclassMarker="AcDbRadialDiametricDimension" TypeString="" BaseClass="DxfDimensionBase" CopyConstructor="Inherited" Tag="Diameter">
    <Property Name="DefinitionPoint2" Code="15" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="15,25,35" />
    <Property Name="LeaderLength" Code="40" Type="double" DefaultValue="0.0" />
  </Entity>
  <!-- radial; type 4 -->
  <Entity Name="DxfRadialDimension" EntityType="Dimension" SubclassMarker="AcDbRadialDimension" TypeString="" BaseClass="DxfDimensionBase" CopyConstructor="Inherited" Tag="Radius">
    <Property Name="DefinitionPoint2" Code="15" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="15,25,35" />
    <Property Name="LeaderLength" Code="40" Type="double" DefaultValue="0.0" />
  </Entity>
  <!-- angular, 3 point; type 5 -->
  <Entity Name="DxfAngularThreePointDimension" EntityType="Dimension" SubclassMarker="AcDbRadialDimension" TypeString="" BaseClass="DxfDimensionBase" CopyConstructor="Inherited" Tag="AngularThreePoint">
    <Property Name="DefinitionPoint2" Code="13" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="13,23,33" />
    <Property Name="DefinitionPoint3" Code="14" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="14,24,34" />
    <Property Name="DefinitionPoint4" Code="15" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="15,25,35" />
    <Property Name="DefinitionPoint5" Code="16" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="16,26,36" />
  </Entity>
  <!-- ordinate; type 6 -->
  <Entity Name="DxfOrdinateDimension" EntityType="Dimension" SubclassMarker="AcDbOrdinateDimension" TypeString="" BaseClass="DxfDimensionBase" CopyConstructor="Inherited" Tag="Ordinate" MinVersion="R12">
    <Property Name="DefinitionPoint2" Code="13" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="13,23,33" />
    <Property Name="DefinitionPoint3" Code="14" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="14,24,34" />
  </Entity>
  <!--
  
  ELLIPSE
  
  -->
  <Entity Name="DxfEllipse" EntityType="Ellipse" SubclassMarker="AcDbEllipse" TypeString="ELLIPSE" MinVersion="R13">
    <Property Name="Center" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="MajorAxis" Code="11" Type="DxfVector" DefaultValue="DxfVector.XAxis" CodeOverrides="11,21,31" />
    <Property Name="Normal" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Property Name="MinorAxisRatio" Code="40" Type="double" DefaultValue="1.0" />
    <Property Name="StartParameter" Code="41" Type="double" DefaultValue="0.0" />
    <Property Name="EndParameter" Code="42" Type="double" DefaultValue="Math.PI * 2" />
    <Constructor>
      <ConstructorParameter Property="Center" Type="DxfPoint" />
      <ConstructorParameter Property="MajorAxis" Type="DxfVector" />
      <ConstructorParameter Property="MinorAxisRatio" Type="double" />
    </Constructor>
  </Entity>
  <!--
  
  HATCH
  
  -->
  <!-- TODO MinVersion="R14" -->
  <!--
  
  IMAGE
  
  -->
  <Entity Name="DxfImage" EntityType="Image" SubclassMarker="AcDbRasterImage" TypeString="IMAGE" MinVersion="R14">
    <Property Name="ClassVersion" Code="90" Type="int" DefaultValue="0" />
    <Property Name="Location" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="UVector" Code="11" Type="DxfVector" DefaultValue="DxfVector.XAxis" CodeOverrides="11,21,31" />
    <Property Name="VVector" Code="12" Type="DxfVector" DefaultValue="DxfVector.YAxis" CodeOverrides="12,22,32" />
    <Property Name="ImageSize" Code="13" Type="DxfVector" DefaultValue="DxfVector.Zero" CodeOverrides="13,23" />
    <Property Name="ImageDefReference" Code="340" Type="string" DefaultValue="null" />
    <Property Name="DisplayOptionsFlags" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)">
      <Flag Name="ShowImage" Mask="1" />
      <Flag Name="ShowImageWhenNotAligned" Mask="2" />
      <Flag Name="UseClippingBoundary" Mask="4" />
      <Flag Name="UseTransparency" Mask="8" />
    </Property>
    <Property Name="UseClipping" Code="280" Type="bool" DefaultValue="true" ReadConverter="BoolShort" WriteConverter="BoolShort" />
    <Property Name="Brightness" Code="281" Type="short" DefaultValue="50" />
    <Property Name="Contrast" Code="282" Type="short" DefaultValue="50" />
    <Property Name="Fade" Code="283" Type="short" DefaultValue="0" />
    <Property Name="ImageDefReactorReference" Code="360" Type="string" DefaultValue="null" />
    <Property Name="ClippingType" Code="71" Type="DxfImageClippingBoundaryType" DefaultValue="DxfImageClippingBoundaryType.Rectangular" ReadConverter="(DxfImageClippingBoundaryType)" WriteConverter="(short)" />
    <Property Name="ClippingVertexCount" Code="91" Type="int" DefaultValue="0" />
    <Property Name="ClippingVerticesX" Code="14" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" />
    <Property Name="ClippingVerticesY" Code="24" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value="AcDbRasterImage" />
      <WriteProperty Property="ClassVersion" />
      <WriteProperty Property="Location" />
      <WriteProperty Property="UVector" />
      <WriteProperty Property="VVector" />
      <WriteProperty Property="ImageSize" />
      <WriteProperty Property="ImageDefReference" />
      <WriteProperty Property="DisplayOptionsFlags" />
      <WriteProperty Property="UseClipping" />
      <WriteProperty Property="Brightness" />
      <WriteProperty Property="Contrast" />
      <WriteProperty Property="Fade" />
      <WriteProperty Property="ImageDefReactorReference" />
      <WriteProperty Property="ClippingType" />
      <WriteSpecificValue Code="91" Value="ClippingVertices.Count" />
      <Foreach Property="ClippingVertices">
        <WriteSpecificValue Code="14" Value="item.X" />
        <WriteSpecificValue Code="24" Value="item.Y" />
      </Foreach>
    </WriteOrder>
  </Entity>
  <!--
  
  INSERT
  
  -->
  <Entity Name="DxfInsert" EntityType="Insert" SubclassMarker="AcDbBlockReference" TypeString="INSERT">
    <Property Name="HasAttributes" Code="66" Type="bool" DefaultValue="false" ReadConverter="BoolShort" WriteConverter="BoolShort" DisableWritingDefault="true" />
    <Property Name="Name" Code="2" Type="string" DefaultValue="null" />
    <Property Name="Location" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="XScaleFactor" Code="41" Type="double" DefaultValue="1.0" DisableWritingDefault="true" />
    <Property Name="YScaleFactor" Code="42" Type="double" DefaultValue="1.0" DisableWritingDefault="true" />
    <Property Name="ZScaleFactor" Code="43" Type="double" DefaultValue="1.0" DisableWritingDefault="true" />
    <Property Name="Rotation" Code="50" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="ColumnCount" Code="70" Type="short" DefaultValue="1" DisableWritingDefault="true" />
    <Property Name="RowCount" Code="71" Type="short" DefaultValue="1" DisableWritingDefault="true" />
    <Property Name="ColumnSpacing" Code="44" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="RowSpacing" Code="45" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" CodeOverrides="210,220,230" />
  </Entity>
  <!--
  
  LEADER
  
  -->
  <Entity Name="DxfLeader" EntityType="Leader" SubclassMarker="AcDbLeader" TypeString="LEADER" MinVersion="R13">
    <Property Name="DimensionStyleName" Code="3" Type="string" DefaultValue="null" />
    <Property Name="UseArrowheads" Code="71" Type="bool" DefaultValue="true" ReadConverter="BoolShort" WriteConverter="BoolShort" />
    <Property Name="PathType" Code="72" Type="DxfLeaderPathType" DefaultValue="DxfLeaderPathType.StraightLineSegments" ReadConverter="(DxfLeaderPathType)" WriteConverter="(short)" />
    <Property Name="AnnotationType" Code="73" Type="DxfLeaderCreationAnnotationType" DefaultValue="DxfLeaderCreationAnnotationType.NoAnnotation" ReadConverter="(DxfLeaderCreationAnnotationType)" WriteConverter="(short)" />
    <Property Name="HooklineDirection" Code="74" Type="DxfLeaderHooklineDirection" DefaultValue="DxfLeaderHooklineDirection.OppositeFromHorizontalVector" ReadConverter="(DxfLeaderHooklineDirection)" WriteConverter="(short)" />
    <Property Name="UseHookline" Code="75" Type="bool" DefaultValue="true" ReadConverter="BoolShort" WriteConverter="BoolShort" />
    <Property Name="TextAnnotationHeight" Code="40" Type="double" DefaultValue="1.0" />
    <Property Name="TextAnnotationWidth" Code="41" Type="double" DefaultValue="1.0" />
    <Property Name="VertexCount" Code="76" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" />
    <Property Name="VerticesX" Code="10" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" />
    <Property Name="VerticesY" Code="20" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" />
    <Property Name="VerticesZ" Code="30" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" />
    <Property Name="OverrideColor" Code="77" Type="DxfColor" DefaultValue="DxfColor.ByBlock" DisableWritingDefault="true" ReadConverter="DxfColor.FromRawValue" WriteConverter="DxfColor.GetRawValue" />
    <Property Name="AssociatedAnnotationReference" Code="340" Type="string" DefaultValue="null" />
    <Property Name="Normal" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" CodeOverrides="210,220,230" />
    <Property Name="Right" Code="211" Type="DxfVector" DefaultValue="DxfVector.XAxis" CodeOverrides="211,221,231" />
    <Property Name="BlockOffset" Code="212" Type="DxfVector" DefaultValue="DxfVector.Zero" CodeOverrides="212,222,232" />
    <Property Name="AnnotationOffset" Code="213" Type="DxfVector" DefaultValue="DxfVector.XAxis" CodeOverrides="213,223,233" MinVersion="R14" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value="AcDbLeader" />
      <WriteProperty Property="DimensionStyleName" />
      <WriteProperty Property="UseArrowheads" />
      <WriteProperty Property="PathType" />
      <WriteProperty Property="AnnotationType" />
      <WriteProperty Property="HooklineDirection" />
      <WriteProperty Property="UseHookline" />
      <WriteProperty Property="TextAnnotationHeight" />
      <WriteProperty Property="TextAnnotationWidth" />
      <WriteSpecificValue Code="76" Value="(short)Vertices.Count" />
      <Foreach Property="Vertices">
        <WriteSpecificValue Code="10" Value="item.X" />
        <WriteSpecificValue Code="20" Value="item.Y" />
        <WriteSpecificValue Code="30" Value="item.Z" />
      </Foreach>
      <WriteProperty Property="OverrideColor" />
      <WriteProperty Property="AssociatedAnnotationReference" />
      <WriteProperty Property="Normal" />
      <WriteProperty Property="Right" />
      <WriteProperty Property="BlockOffset" />
      <WriteProperty Property="AnnotationOffset" />
    </WriteOrder>
  </Entity>
  <!--
  
  LINE
  
  -->
  <Entity Name="DxfLine" EntityType="Line" SubclassMarker="AcDbLine" TypeString="LINE,3DLINE">
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="P1" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="P2" Code="11" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="11,21,31" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Constructor>
      <ConstructorParameter Property="P1" Type="DxfPoint" />
      <ConstructorParameter Property="P2" Type="DxfPoint" />
    </Constructor>
  </Entity>
  <!--
  
  LWPOLYLINE
  
  -->
  <Entity Name="DxfLwPolyline" EntityType="LwPolyline" SubclassMarker="AcDbPolyline" TypeString="LWPOLYLINE" MinVersion="R14">
    <Property Name="VertexCount" Code="90" Type="int" DefaultValue="0" />
    <Property Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)">
      <Flag Name="IsClosed" Mask="1" />
      <Flag Name="IsPLineGen" Mask="128" />
    </Property>
    <Property Name="ConstantWidth" Code="43" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="VertexCoordinateX" Code="10" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" />
    <Property Name="VertexCoordinateY" Code="20" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" />
    <Property Name="StartingWidth" Code="40" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" DisableWritingDefault="true" />
    <Property Name="EndingWidth" Code="41" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" DisableWritingDefault="true" />
    <Property Name="Bulge" Code="42" Type="double" DefaultValue="" Accessibility="private" AllowMultiples="true" DisableWritingDefault="true" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value="AcDbPolyline" />
      <WriteSpecificValue Code="90" Value="Vertices.Count" />
      <WriteProperty Property="Flags" />
      <WriteProperty Property="ConstantWidth" />
      <WriteSpecificValue Code="38" Value="Elevation" DontWriteIfValueIs="0.0" />
      <WriteProperty Property="Thickness" />
      <Foreach Property="Vertices">
        <WriteSpecificValue Code="10" Value="item.Location.X" />
        <WriteSpecificValue Code="20" Value="item.Location.Y" />
        <WriteSpecificValue Code="40" Value="item.StartingWidth" DontWriteIfValueIs="0.0" />
        <WriteSpecificValue Code="41" Value="item.EndingWidth" DontWriteIfValueIs="0.0" />
        <WriteSpecificValue Code="42" Value="item.Bulge" DontWriteIfValueIs="0.0" />
      </Foreach>
      <WriteProperty Property="ExtrusionDirection" />
    </WriteOrder>
  </Entity>
  <!--
  
  MLINE
  
  -->
  <!-- TODO -->
  <!--
  
  MTEXT
  
  -->
  <!-- TODO -->
  <!--
  
  OLEFRAME
  
  -->
  <Entity Name="DxfOleFrame" EntityType="OleFrame" SubclassMarker="AcDbOleFrame" TypeString="OLEFRAME" MinVersion="R13">
    <Property Name="VersionNumber" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" />
    <Property Name="BinaryDataLength" Code="90" Type="int" DefaultValue="0" />
    <Property Name="BinaryDataStrings" Code="310" Type="string" DefaultValue="" AllowMultiples="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value="AcDbOleFrame" />
      <WriteProperty Property="VersionNumber" />
      <WriteProperty Property="BinaryDataLength" />
      <Foreach Property="BinaryDataStrings">
        <WriteSpecificValue Code="310" Value="item" />
      </Foreach>
      <WriteSpecificValue Code="1" Value="OLE" />
    </WriteOrder>
  </Entity>
  <!--
  
  OLE2FRAME
  
  -->
  <Entity Name="DxfOle2Frame" EntityType="Ole2Frame" SubclassMarker="AcDbOle2Frame" TypeString="OLE2FRAME" MinVersion="R14">
    <Property Name="VersionNumber" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" />
    <Property Name="Description" Code="3" Type="string" DefaultValue="null" />
    <Property Name="UpperLeftCorner" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="LowerRightCorner" Code="11" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="11,21,31" />
    <Property Name="ObjectType" Code="71" Type="DxfOleObjectType" DefaultValue="DxfOleObjectType.Static" ReadConverter="(DxfOleObjectType)" WriteConverter="(short)" />
    <Property Name="TileMode" Code="72" Type="DxfTileModeDescriptor" DefaultValue="DxfTileModeDescriptor.InTiledViewport" ReadConverter="(DxfTileModeDescriptor)" WriteConverter="(short)" />
    <Property Name="BinaryDataLength" Code="90" Type="int" DefaultValue="0" />
    <Property Name="BinaryDataStrings" Code="310" Type="string" DefaultValue="" AllowMultiples="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value="AcDbOle2Frame" />
      <WriteProperty Property="VersionNumber" />
      <WriteProperty Property="Description" />
      <WriteProperty Property="UpperLeftCorner" />
      <WriteProperty Property="LowerRightCorner" />
      <WriteProperty Property="ObjectType" />
      <WriteProperty Property="TileMode" />
      <WriteProperty Property="BinaryDataLength" />
      <Foreach Property="BinaryDataStrings">
        <WriteSpecificValue Code="310" Value="item" />
      </Foreach>
      <WriteSpecificValue Code="1" Value="OLE" />
    </WriteOrder>
  </Entity>
  <!--
  
  POINT
  
  -->
  <Entity Name="DxfModelPoint" EntityType="Point" SubclassMarker="AcDbPoint" TypeString="POINT">
    <Property Name="Location" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Property Name="Angle" Code="50" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Constructor>
      <ConstructorParameter Property="Location" Type="DxfPoint" />
    </Constructor>
  </Entity>
  <!--
  
  POLYLINE
  
  -->
  <Entity Name="DxfPolyline" EntityType="Polyline" SubclassMarker="AcDb2dPolyline" TypeString="POLYLINE">
    <Property Name="ContainsVertices" Code="66" Type="bool" DefaultValue="true" ReadConverter="BoolShort" WriteConverter="BoolShort" MaxVersion="R13" />
    <Property Name="Location" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" MinVersion="R12" />
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" DisableWritingDefault="true">
      <Flag Name="IsClosed" Mask="1" />
      <Flag Name="CurveFitVerticiesAdded" Mask="2" />
      <Flag Name="SplineFitVerticiesAdded" Mask="4" />
      <Flag Name="Is3DPolyline" Mask="8" />
      <Flag Name="Is3DPolygonMesh" Mask="16" />
      <Flag Name="IsPolygonMeshClosedInNDirection" Mask="32" />
      <Flag Name="IsPolyfaceMesh" Mask="64" />
      <Flag Name="IsLinetypePatternGeneratedContinuously" Mask="128" />
    </Property>
    <Property Name="DefaultStartingWidth" Code="40" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="DefaultEndingWidth" Code="41" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="PolygonMeshMVertexCount" Code="71" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" DisableWritingDefault="true" />
    <Property Name="PolygonMeshNVertexCount" Code="72" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" DisableWritingDefault="true" />
    <Property Name="SmoothSurfaceMDensity" Code="73" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" DisableWritingDefault="true" />
    <Property Name="SmoothSurfaceNDensity" Code="74" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" DisableWritingDefault="true" />
    <Property Name="SurfaceType" Code="75" Type="DxfPolylineCurvedAndSmoothSurfaceType" DefaultValue="DxfPolylineCurvedAndSmoothSurfaceType.None" ReadConverter="(DxfPolylineCurvedAndSmoothSurfaceType)" WriteConverter="(short)" DisableWritingDefault="true" />
    <Property Name="Normal" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--
  
  RAY
  
  -->
  <Entity Name="DxfRay" EntityType="Ray" SubclassMarker="AcDbRay" TypeString="RAY" MinVersion="R13">
    <Property Name="StartPoint" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="UnitDirectionVector" Code="11" Type="DxfVector" DefaultValue="DxfVector.XAxis" CodeOverrides="11,21,31" />
    <Constructor>
      <ConstructorParameter Property="StartPoint" Type="DxfPoint" />
      <ConstructorParameter Property="UnitDirectionVector" Type="DxfVector" />
    </Constructor>
  </Entity>
  <!--
  
  REGION
  
  -->
  <Entity Name="DxfRegion" EntityType="Region" SubclassMarker="AcDbModelerGeometry" TypeString="REGION" MinVersion="R13">
    <Property Name="FormatVersionNumber" Code="70" Type="short" DefaultValue="1" />
    <Property Name="CustomData" Code="1" Type="string" DefaultValue="null" AllowMultiples="true" />
    <Property Name="CustomData2" Code="3" Type="string" DefaultValue="null" AllowMultiples="true" />
  </Entity>
  <!--
  
  RTEXT
  
  -->
  <Entity Name="DxfRText" EntityType="RText" SubclassMarker="RText" TypeString="RTEXT" MinVersion="R2000">
    <Property Name="InsertionPoint" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Property Name="RotationAngle" Code="50" Type="double" DefaultValue="0.0" />
    <Property Name="TextHeight" Code="40" Type="double" DefaultValue="0.0" />
    <Property Name="TextStyle" Code="7" Type="string" DefaultValue="null" />
    <Property Name="TypeFlags" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)">
      <Flag Name="IsExpression" Mask="1" />
      <Flag Name="IsInlineMTextSequencesEnabled" Mask="2" />
    </Property>
    <Property Name="Contents" Code="1" Type="string" DefaultValue="null" />
  </Entity>
  <!--
  
  SEQEND
  
  -->
  <Entity Name="DxfSeqend" EntityType="Seqend" SubclassMarker="null" TypeString="SEQEND"></Entity>
  <!--
  
  SHAPE
  
  -->
  <Entity Name="DxfShape" EntityType="Shape" SubclassMarker="AcDbShape" TypeString="SHAPE">
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Location" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="Size" Code="40" Type="double" DefaultValue="0.0" />
    <Property Name="Name" Code="2" Type="string" DefaultValue="null" />
    <Property Name="RotationAngle" Code="50" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="RelativeXScaleFactor" Code="41" Type="double" DefaultValue="1.0" DisableWritingDefault="true" />
    <Property Name="ObliqueAngle" Code="51" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--
  
  SOLID
  
  -->
  <Entity Name="DxfSolid" EntityType="Solid" SubclassMarker="AcDbShape" TypeString="SOLID">
    <Property Name="FirstCorner" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="SecondCorner" Code="11" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="11,21,31" />
    <Property Name="ThirdCorner" Code="12" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="12,22,32" />
    <Property Name="FourthCorner" Code="13" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="13,23,33" />
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--
  
  SPLINE
  
  -->
  <Entity Name="DxfSpline" EntityType="Spline" SubclassMarker="AcDbSpline" TypeString="SPLINE" MinVersion="R13">
    <Property Name="Normal" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" CodeOverrides="210,220,230" />
    <Property Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)">
      <Flag Name="IsClosed" Mask="1" />
      <Flag Name="IsPeriodic" Mask="2" />
      <Flag Name="IsRational" Mask="4" />
      <Flag Name="IsPlanar" Mask="8" />
      <Flag Name="IsLinear" Mask="16" />
    </Property>
    <Property Name="DegreeOfCurve" Code="71" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" />
    <Property Name="NumberOfKnotsIgnored" Code="72" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" Accessibility="private" />
    <Property Name="NumberOfControlPointsIgnored" Code="73" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" Accessibility="private" />
    <Property Name="NumberOfFitPointsIgnored" Code="74" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" Accessibility="private" />
    <Property Name="KnotTolerance" Code="42" Type="double" DefaultValue="0.0000001" DisableWritingDefault="true" />
    <Property Name="ControlPointTolerance" Code="43" Type="double" DefaultValue="0.0000001" DisableWritingDefault="true" />
    <Property Name="FitTolerance" Code="44" Type="double" DefaultValue="0.0000000001" DisableWritingDefault="true" />
    <Property Name="StartTangent" Code="12" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="12,22,32" />
    <Property Name="EndTangent" Code="13" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="13,23,33" />
    <Property Name="KnotValues" Code="40" Type="double" DefaultValue="" AllowMultiples="true" />
    <Property Name="Weight" Code="41" Type="double" DefaultValue="1.0" DisableWritingDefault="true" />
    <Property Name="ControlPointX" Code="10" Type="double" DefaultValue="" AllowMultiples="true" Accessibility="private" />
    <Property Name="ControlPointY" Code="20" Type="double" DefaultValue="" AllowMultiples="true" Accessibility="private" />
    <Property Name="ControlPointZ" Code="30" Type="double" DefaultValue="" AllowMultiples="true" Accessibility="private" />
    <Property Name="FitPointX" Code="11" Type="double" DefaultValue="" AllowMultiples="true" Accessibility="private" />
    <Property Name="FitPointY" Code="21" Type="double" DefaultValue="" AllowMultiples="true" Accessibility="private" />
    <Property Name="FitPointZ" Code="31" Type="double" DefaultValue="" AllowMultiples="true" Accessibility="private" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value="AcDbSpline" />
      <WriteProperty Property="Normal" />
      <WriteProperty Property="Flags" />
      <WriteSpecificValue Code="72" Value="(short)KnotValues.Count" />
      <WriteSpecificValue Code="73" Value="(short)ControlPoints.Count" />
      <WriteSpecificValue Code="74" Value="(short)FitPoints.Count" />
      <WriteProperty Property="KnotTolerance" />
      <WriteProperty Property="ControlPointTolerance" />
      <WriteProperty Property="FitTolerance" />
      <WriteProperty Property="StartTangent" />
      <WriteProperty Property="EndTangent" />
      <WriteProperty Property="KnotValues" />
      <WriteProperty Property="Weight" />
      <Foreach Property="ControlPoints">
        <WriteSpecificValue Code="10" Value="item.X" />
        <WriteSpecificValue Code="20" Value="item.Y" />
        <WriteSpecificValue Code="30" Value="item.Z" />
      </Foreach>
      <Foreach Property="FitPoints">
        <WriteSpecificValue Code="11" Value="item.X" />
        <WriteSpecificValue Code="21" Value="item.Y" />
        <WriteSpecificValue Code="31" Value="item.Z" />
      </Foreach>
    </WriteOrder>
  </Entity>
  <!--
  
  TEXT
  
  -->
  <Entity Name="DxfText" EntityType="Text" SubclassMarker="AcDbText" TypeString="TEXT">
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Location" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="TextHeight" Code="40" Type="double" DefaultValue="1.0" />
    <Property Name="Value" Code="1" Type="string" DefaultValue="null" />
    <Property Name="Rotation" Code="50" Type="double" DefaultValue="0" DisableWritingDefault="true" />
    <Property Name="RelativeXScaleFactor" Code="41" Type="double" DefaultValue="1.0" DisableWritingDefault="true" />
    <Property Name="ObliqueAngle" Code="51" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="TextStyleName" Code="7" Type="string" DefaultValue="STANDARD" DisableWritingDefault="true" />
    <Property Name="TextGenerationFlags" Code="71" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)" DisableWritingDefault="true">
      <Flag Name="IsTextBackward" Mask="2" />
      <Flag Name="IsTextUpsideDown" Mask="4" />
    </Property>
    <Property Name="HorizontalTextJustification" Code="72" Type="DxfHorizontalTextJustification" DefaultValue="DxfHorizontalTextJustification.Left" ReadConverter="(DxfHorizontalTextJustification)" WriteConverter="(short)" DisableWritingDefault="true" />
    <Property Name="SecondAlignmentPoint" Code="11" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="11,21,31" />
    <Property Name="Normal" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Property Name="VerticalTextJustification" Code="73" Type="DxfVerticalTextJustification" DefaultValue="DxfVerticalTextJustification.Baseline" ReadConverter="(DxfVerticalTextJustification)" WriteConverter="(short)" DisableWritingDefault="true" />
    <Constructor>
      <ConstructorParameter Property="Location" Type="DxfPoint" />
      <ConstructorParameter Property="TextHeight" Type="double" />
      <ConstructorParameter Property="Value" Type="string" />
    </Constructor>
  </Entity>
  <!--
  
  TOLERANCE
  
  -->
  <Entity Name="DxfTolerance" EntityType="Tolerance" SubclassMarker="AcDbFcf" TypeString="TOLERANCE" MinVersion="R13">
    <Property Name="DimensionStyleName" Code="3" Type="string" DefaultValue="null" />
    <Property Name="InsertionPoint" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Property Name="DirectionVector" Code="11" Type="DxfVector" DefaultValue="DxfVector.XAxis" CodeOverrides="11,21,31" />
  </Entity>
  <!--
  
  TRACE
  
  -->
  <Entity Name="DxfTrace" EntityType="Trace" SubclassMarker="AcDbTrace" TypeString="TRACE">
    <Property Name="FirstCorner" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="SecondCorner" Code="11" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="11,21,31" />
    <Property Name="ThirdCorner" Code="12" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="12,22,32" />
    <Property Name="FourthCorner" Code="13" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="13,23,33" />
    <Property Name="Thickness" Code="39" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="ExtrusionDirection" Code="210" Type="DxfVector" DefaultValue="DxfVector.ZAxis" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--
  
  VERTEX
  
  -->
  <Entity Name="DxfVertex" EntityType="Vertex" SubclassMarker="AcDbVertex" TypeString="VERTEX">
    <Property Name="Location" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="StartingWidth" Code="40" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="EndingWidth" Code="41" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Bulge" Code="42" Type="double" DefaultValue="0.0" DisableWritingDefault="true" />
    <Property Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="(int)" WriteConverter="(short)">
      <Flag Name="IsExtraCreatedByCurveFit" Mask="1" />
      <Flag Name="IsCurveFitTangentDefined" Mask="2" />
      <Flag Name="IsSplineVertexCreatedBySplineFitting" Mask="8" />
      <Flag Name="IsSplineFrameControlPoint" Mask="16" />
      <Flag Name="Is3DPolylineVertex" Mask="32" />
      <Flag Name="Is3DPolygonMesh" Mask="64" />
      <Flag Name="IsPolyfaceMeshVertex" Mask="128" />
    </Property>
    <Property Name="CurveFitTangentDirection" Code="50" Type="double" DefaultValue="0.0" />
    <Property Name="PolyfaceMeshVertexIndex1" Code="71" Type="int" DefaultValue="0" DisableWritingDefault="true" ReadConverter="(int)" WriteConverter="(short)" MinVersion="R13" />
    <Property Name="PolyfaceMeshVertexIndex2" Code="72" Type="int" DefaultValue="0" DisableWritingDefault="true" ReadConverter="(int)" WriteConverter="(short)" MinVersion="R13" />
    <Property Name="PolyfaceMeshVertexIndex3" Code="73" Type="int" DefaultValue="0" DisableWritingDefault="true" ReadConverter="(int)" WriteConverter="(short)" MinVersion="R13" />
    <Property Name="PolyfaceMeshVertexIndex4" Code="74" Type="int" DefaultValue="0" DisableWritingDefault="true" ReadConverter="(int)" WriteConverter="(short)" MinVersion="R13" />
    <Constructor>
      <ConstructorParameter Property="Location" Type="DxfPoint" />
    </Constructor>
  </Entity>
  <!--
  
  VIEWPORT
  
  -->
  <!-- TODO MinVersion="R12" -->
  <!--
  
  WIPEOUT
  
  -->
  <Entity Name="DxfWipeout" EntityType="WipeOut" SubclassMarker="AcDbWipeout" TypeString="WIPEOUT" BaseClass="DxfImage" MinVersion="R2000">
    <!-- wholly inherits from IMAGE -->
  </Entity>
  <!--
  
  XLINE
  
  -->
  <Entity Name="DxfXLine" EntityType="XLine" SubclassMarker="AcDbXline" TypeString="XLINE" MinVersion="R13">
    <Property Name="FirstPoint" Code="10" Type="DxfPoint" DefaultValue="DxfPoint.Origin" CodeOverrides="10,20,30" />
    <Property Name="UnitDirectionVector" Code="11" Type="DxfVector" DefaultValue="DxfVector.XAxis" CodeOverrides="11,21,31" />
    <Constructor>
      <ConstructorParameter Property="FirstPoint" Type="DxfPoint" />
      <ConstructorParameter Property="UnitDirectionVector" Type="DxfVector" />
    </Constructor>
  </Entity>
</Spec>
